name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
    - name: Lint with flake8
      run: |
        flake8 app/ tests/ e2e_tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 app/ tests/ e2e_tests/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check formatting with black
      run: |
        black --check app/ tests/ e2e_tests/
    - name: Check imports with isort
      run: |
        isort --check-only --profile black app/ tests/ e2e_tests/
